[tool.poetry]
name = "common"
version = "0.1.0"
description = ""
authors = ["Mehmet Eren Balasar <balasar@ratioenergy.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
