MODEL_TIME_INTERVAL_SECONDS = 60 * 60 * 24 * 7  # 1 week

HECTARE = "ha"
DECARE = "da"
M2 = "m2"

MAX_CROPS = 5

DATE_COL = "date"
DATE_FORMAT = "%Y-%m-%d"

SEED_PRICE_COL = "seed_price"

PLANTING_LABOR_PRICE_COL = "planting_labor_price"
MAINTENANCE_LABOR_PRICE_COL = "maintenance_labor_price"
HARVESTING_LABOR_PRICE_COL = "harvesting_labor_price"

MACHINERY_PRICE_COL = "machinery_price"

# N_FERTILIZER_PRICE_COL = "nitrogen_fertilizer_price"
# P_FERTILIZER_PRICE_COL = "phosphorus_fertilizer_price"
# K_FERTILIZER_PRICE_COL = "potassium_fertilizer_price"
FERTILIZER_PRICE_COL = "fertilizer_price"

PESTICIDE_PRICE_COL = "pesticide_price"

TRANSPORTATION_PRICE_COL = "transportation_price"

IRRIGATION_PRICE_COL = "irrigation_price"

MARKET_PRICE_COL = "market_price"

# !! WEATHER FILE IS NOT IMPLEMENTED YET

# === File structures ===
SEED_FILE = {DATE_COL, SEED_PRICE_COL}
LABOR_FILE = {
    DATE_COL,
    PLANTING_LABOR_PRICE_COL,
    MAINTENANCE_LABOR_PRICE_COL,
    HARVESTING_LABOR_PRICE_COL,
}
MACHINERY_FILE = {DATE_COL, MACHINERY_PRICE_COL}
IRRIGATION_FILE = {DATE_COL, IRRIGATION_PRICE_COL}
# FERTILIZER_FILE = {
#     DATE_COL,
#     N_FERTILIZER_PRICE_COL,
#     P_FERTILIZER_PRICE_COL,
#     K_FERTILIZER_PRICE_COL,
# } # not now
FERTILIZER_FILE = {DATE_COL, FERTILIZER_PRICE_COL}
PESTICIDE_FILE = {DATE_COL, PESTICIDE_PRICE_COL}
LOGISTICS_FILE = {DATE_COL, TRANSPORTATION_PRICE_COL}
MARKET_FILE = {DATE_COL, MARKET_PRICE_COL}
WEATHER_FILE = {DATE_COL}  #!! Not implemented yet
